import 'package:flutter/material.dart';

final List<Map<String, dynamic>> kidsDentalVideos = [
  {
    'title': 'Brush Your Teeth Song for Kids',
    'shortTitle': 'Brush Your Teeth Song',
    'subtitle': 'Animated brushing lesson',
    'duration': '4 min',
    'category': 'Brushing',
    'tag': 'Kids',
    'description':
        'A short child-friendly brushing lesson for building a simple morning and night routine.',
    'tip': 'Brush in small circles for two minutes, twice a day.',
    'icon': Icons.health_and_safety_outlined,
    'color': Colors.blue,
  },
  {
    'title': 'Why Do We Brush Our Teeth?',
    'shortTitle': 'Why Brush Teeth?',
    'subtitle': 'Cavity care for children',
    'duration': '5 min',
    'category': 'Cavity Care',
    'tag': 'Care',
    'description':
        'A simple lesson about plaque, germs, and how brushing protects teeth from cavities.',
    'tip': 'After sweets, drink water and brush when it is brushing time.',
    'icon': Icons.bug_report_outlined,
    'color': Colors.green,
  },
  {
    'title': 'A Visit to the Dentist',
    'shortTitle': 'Dentist Visit',
    'subtitle': 'Friendly checkup guide',
    'duration': '6 min',
    'category': 'Dental Visit',
    'tag': 'Visit',
    'description':
        'A gentle guide to help children feel comfortable before a dental checkup.',
    'tip': 'A dentist visit is a tooth checkup, not something to fear.',
    'icon': Icons.sentiment_satisfied_alt,
    'color': Colors.orange,
  },
  {
    'title': 'Healthy Snacks for Teeth',
    'shortTitle': 'Healthy Snacks',
    'subtitle': 'Food choices for smiles',
    'duration': '5 min',
    'category': 'Food Care',
    'tag': 'Food',
    'description':
        'A quick lesson about choosing foods and drinks that are kinder to teeth.',
    'tip': 'Crunchy fruits, water, and milk are better choices for teeth.',
    'icon': Icons.restaurant_menu,
    'color': Colors.purple,
  },
  {
    'title': 'Two Minute Brush Timer',
    'shortTitle': 'Brush Timer',
    'subtitle': 'Practice brushing time',
    'duration': '2 min',
    'category': 'Routine',
    'tag': 'Timer',
    'description':
        'A timer-style video to help children brush long enough every day.',
    'tip': 'Use a timer so every part of your mouth gets cleaned.',
    'icon': Icons.timer_outlined,
    'color': Colors.cyan,
  },
  {
    'title': 'Flossing for Little Teeth',
    'shortTitle': 'Flossing Lesson',
    'subtitle': 'Cleaning between teeth',
    'duration': '4 min',
    'category': 'Flossing',
    'tag': 'Floss',
    'description':
        'A simple introduction to flossing and cleaning between teeth.',
    'tip': 'Floss gently and ask an adult for help when needed.',
    'icon': Icons.clean_hands_outlined,
    'color': Colors.teal,
  },
  {
    'title': 'Brushy Brush with Sesame Street',
    'shortTitle': 'Brushy Brush',
    'subtitle': 'Fun tooth brushing song',
    'duration': '2 min',
    'category': 'Brushing',
    'tag': 'Song',
    'description':
        'A playful song that reminds kids to brush all around their teeth every morning and night.',
    'tip': 'Brush the front, back, and chewing parts of every tooth.',
    'icon': Icons.music_note_outlined,
    'color': Colors.red,
  },
  {
    'title': 'How to Brush Your Teeth Properly',
    'shortTitle': 'Brush Properly',
    'subtitle': 'Step-by-step brushing',
    'duration': '4 min',
    'category': 'Brushing',
    'tag': 'Steps',
    'description':
        'A clear kids brushing guide that shows simple steps for cleaning teeth, gums, and tongue.',
    'tip': 'Use gentle circles and reach the back teeth too.',
    'icon': Icons.fact_check_outlined,
    'color': Colors.indigo,
  },
  {
    'title': 'Floss Teeth for Kids Under Age 5',
    'shortTitle': 'Little Kids Floss',
    'subtitle': 'Parent flossing guide',
    'duration': '3 min',
    'category': 'Flossing',
    'tag': 'Under 5',
    'description':
        'A parent-friendly flossing guide for helping younger children clean between little teeth.',
    'tip': 'Ask an adult to help floss where toothbrush bristles cannot reach.',
    'icon': Icons.family_restroom_outlined,
    'color': Colors.deepOrange,
  },
  {
    'title': 'Care for Teeth Ages 3 to 6',
    'shortTitle': 'Ages 3 to 6 Care',
    'subtitle': 'Oral care basics',
    'duration': '6 min',
    'category': 'Oral Care',
    'tag': 'Ages 3-6',
    'description':
        'A friendly oral care lesson for children aged 3 to 6, covering brushing and healthy tooth habits.',
    'tip': 'An adult should help brush until kids can clean every tooth well.',
    'icon': Icons.child_care_outlined,
    'color': Colors.brown,
  },
];
